site_name: Luke Albarracin
nav:
- 'About Me' : index.md
- 'Projects' : projects.md

theme:
  name: material
  hihglightjs: true
  hljs_languages:
    - yaml
    - rust
    - clojure

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

