# https://github.com/stefnestor/demo_mkdocs/blob/f1e247f7e5afcf19c77d9360b82686639f3a01fc/.github/workflows/docs.yml
name: docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build and deploy mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: checkout main 
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
	  pip install -U git+https://github.com/mkdocs/mkdocs.git#egg=mkdocs
          pip install mkdocs-material

      - name: deploy
        run: |
          git pull
          mkdocs gh-deploy --force
	  mkdocs --version
